application: kevincox-cdn
version: 1
runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  static_dir: root/
  http_headers:
    Cache-Control: max-age=31536000, stale-while-revalidate=31536000, stale-on-error=31536000

default_expiration: 365d
